version: '3.1'

services:

  nbatippspiel-db:
    image: mysql:8
    restart: on-failure
    environment:
      MYSQL_DATABASE: playoffs
      MYSQL_USER: playoffs
      MYSQL_PASSWORD: playoffs
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    domainname: localhost
